# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(verbose_name='邮政编码'),
        ),
    ]
